### ISSUE TITLE
API change in Indigo breaks existing code.

### ISSUE THREAD

**Issue by debadeepta** [OctoMap/octomap_msgs#7]
Hi,

It seems there was a drastic change in the API of octomap_msgs in ROS Indigo to support color octrees in the binaryMsgToMap function static inline octomap::AbstractOcTree\* binaryMsgToMap(const Octomap& msg)

But this broke our stable code in a bad way requiring lots of fixes. Even if this was a necessary API change I am confused as to why the return type went back all the way to the AbstractOcTree when it could have just gone to OccupancyOcTreeBase<OcTreeNode>\* type which would have allowed both OcTree and ColorOcTree without such a drastic breakdown in API since OuccupancyOcTreeBase has most of the functionality of classes which derive from it anyways.

I love octomap and a lot of people use it. Please consider not changing the API! :-) :-)

Many thanks,
Dey

**Comment by debadeepta** [comment]
I meant OccupancyOcTreeBase<OcTreeNode>\* instead of AbstractOcTree*

**Comment by ahornung** [comment]
Indeed, there should not have been a breaking change in Indigo, I completely agree with you. It's sometimes a hard tradeoff between not changing anything and carefully adding small features, since Indigo is a LTS version and will thus be used for a long time.

The change was introduced in PR #6 and somehow the (breaking) API change slipped through, sorry for that. What would be the best way to fix it now? Reverting the change will probably introduce many breaking changes again...

**Comment by debadeepta** [comment]
I agree it is a hard trade off! :-)

We have made our code compliant now. So please don't worry about us. I just
wanted to bring it to your attention!
